version: '3.6'
services:
  mongo:
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - auth-app-data:/data/db
    env_file:
      - .env
    # networks:
    #   - mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    # networks:
    #   - mongodb
    depends_on:
      - mongo

# networks:
#   mongodb:
#     driver: bridge
volumes:
  auth-app-data:
